export const testColors = {
  blue: "#007bff",
  indigo: "#6610f2",
  purple: "#6f42c1",
  pink: "#e83e8c",
  red: "#dc3545",
  orange: "#fd7e14",
  yellow: "#ffc107",
  green: "#28a745",
  teal: "#20c997",
  cyan: "#17a2b8",
  white: "#fff",
  gray: "#6c757d",
  grayDark: "#343a40",
  black: "#000",
  themeDark: {
    background: "#2D2D2D",
    accent: "#A07F5D",
    accentHover: "#B58F68",
    textPrimary: "#FCFCFC",
    textSecondary: "#9A9A9A",
    stroke: "#535353",
    error: "#D64747",
  },
};

export const mediaQueries = {
  minTablet: "(min-width: 768px)",
  minLaptop: "(min-width: 1280px)",
  minDesktop: "(min-width: 1550px)",
};

export const IS_ADMIN_PARENT = window.parent.parent !== window.parent.self;

export const COMPONENT_KEYS = {
  PHOTO_TEXT_BUTTON: "PHOTO_TEXT_BUTTON",
  PHOTO_QUOTE: "PHOTO_QUOTE",
  ADVANTAGES: "ADVANTAGES",
  CHARACTERISTICS: "CHARACTERISTICS",
  DOCUMENTATION: "DOCUMENTATION",
  TECHNOLOGIES: "TECHNOLOGIES",
  TERMS: "TERMS",
  TERMS_PHOTO: "TERMS_PHOTO",
  VIDEO: "VIDEO",
  FORM_SUBSCRIBE: "FORM_SUBSCRIBE",
  FORM_SECTION: "FORM_SECTION",
  FORM_MODAL: "FORM_MODAL",
  WELCOME_SLIDER: "WELCOME_SLIDER",
  ADVANTAGES_SLIDER: "ADVANTAGES_SLIDER",
  LOCATION: "LOCATION",
  WELCOME_SLIDER_TEXT: "WELCOME_SLIDER_TEXT",
  PLANNING: "PLANNING",
  CATALOG: "CATALOG",
  TABLE: "TABLE",
  CONSTRUCTION_PROGRESS: "CONSTRUCTION_PROGRESS",
  BLOG_SECTION: "BLOG_SECTION",
  MAP_SECTION: "MAP_SECTION",

  PRIVACY_POLICY: "PRIVACY_POLICY",

  // LAYOUT
  HEADER: "HEADER",
  FOOTER: "FOOTER",

  // SETTINGS
  ARROWS: "ARROWS",
  BUTTONS: "BUTTONS",
  CUSTOM_THEME_COLORS: "CUSTOM_THEME_COLORS",
  TYPOGRAPHIES: "TYPOGRAPHIES",

  // BLOG
  BLOG_PAGE: "BLOG_PAGE",
  BLOG_ALL_PAGE: "BLOG_ALL_PAGE",
  BLOG_SECTION_IMAGE: "BLOG_SECTION_IMAGE",
  BLOG_SECTION_LIST: "BLOG_SECTION_LIST",
  BLOG_SECTION_SLIDER: "BLOG_SECTION_SLIDER",
  BLOG_SECTION_QUOTE: "BLOG_SECTION_QUOTE",
  BLOG_SECTION_VIDEO: "BLOG_SECTION_VIDEO",
  BLOG_SECTION_BUTTON: "BLOG_SECTION_BUTTON",
  BLOG_SECTION_TEXT: "BLOG_SECTION_TEXT",
  BLOG_SECTION_TITLE: "BLOG_SECTION_TITLE",
};

export const COMPONENT_NAMES = {
  SECTIONS: {
    DEFAULT_BLOCK_ADVANTAGES: "DEFAULT_BLOCK_ADVANTAGES",
    DEFAULT_BLOCK_CHARACTERISTICS: "DEFAULT_BLOCK_CHARACTERISTICS",
    DEFAULT_BLOCK_DOCUMENTATION: "DEFAULT_BLOCK_DOCUMENTATION",
    DEFAULT_BLOCK_PHOTO_TEXT_BUTTON: "DEFAULT_BLOCK_PHOTO_TEXT_BUTTON",
    DEFAULT_BLOCK_PHOTO_QUOTE: "DEFAULT_BLOCK_PHOTO_QUOTE",
    DEFAULT_BLOCK_TECHNOLOGIES: "DEFAULT_BLOCK_TECHNOLOGIES",
    DEFAULT_BLOCK_TERMS: "DEFAULT_BLOCK_TERMS",
  },
  SETTINGS: {
    DEFAULT_UI_KIT_ARROWS: "DEFAULT_UI_KIT_ARROWS",
    DEFAULT_UI_KIT_BUTTONS: "DEFAULT_UI_KIT_BUTTONS",
    DEFAULT_UI_KIT_CUSTOM_THEME_COLORS: "DEFAULT_UI_KIT_CUSTOM_THEME_COLORS",
    DEFAULT_UI_KIT_TYPOGRAPHIES: "DEFAULT_UI_KIT_TYPOGRAPHIES",
  },
};

export const placeholderPhotoSrc = "https://i.imgur.com/sIL4ZIZ.png";

export const placeholderPhotoMobileSrc = "https://i.imgur.com/EkjJcms.png";
